# Every field in a theme file is optional.

shadow = false
borders = "simple" # Alternatives are "none" and "simple"

# Base colors are red, green, blue,
# cyan, magenta, yellow, white and black.
[colors]
	background = "#32344a"
	# If the value is an array, the first valid color will be used.
	# If the terminal doesn't support custom color,
	# non-base colors will be skipped.
	shadow     = ["blue"]
	view       = "#32344a"

	# Array and simple values have the same effect.
	primary   = ["white"]
	secondary = "#EEEEEE"
	tertiary  = "#444444"

	# Hex values can use lower or uppercase.
	# (base color MUST be lowercase)
	title_primary   = "blue"
	title_secondary = "#ffff55"

	# Lower precision values can use only 3 digits.
	highlight          = "#F88"
	highlight_inactive = "#5555FF"
